$image = {{image}}
<* for name, value in colors *>
${{name}} = rgba({{value.default.hex_stripped}}ff)
<* endfor *>
$active_border = rgba({{ colors.outline_variant.default.hex | to_color | format: "hex_stripped" }}ff)
$inactive_border = rgba({{ colors.outline_variant.default.hex | to_color | set_lightness: 10 | format: "hex_stripped" }}aa)
